# Generated by Django 5.0.14 on 2026-06-29 11:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_backfill_default_space'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('org_admin', 'Organization Admin'), ('business_admin', 'Business Admin')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_line', models.ForeignKey(blank=True, help_text='Required for business_admin; ignored for org_admin.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_memberships', to='spaces.businessline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_memberships', to='spaces.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'spaces_organizationmembership',
                'unique_together': {('user', 'organization', 'business_line', 'role')},
            },
        ),
    ]
