# Generated by Django 5.0.14 on 2026-07-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_rename_knowledge_doc_content_hash_idx_knowledge_d_content_979d1d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('html', 'HTML'), ('txt', 'Plain Text'), ('md', 'Markdown')], max_length=10),
        ),
    ]
